export const PA_CONCERN_UPDATE = 'PA_CONCERN_UPDATE'
export const PA_CURRENT_COVERAGE_ANSWER = 'PA_CURRENT_COVERAGE_ANSWER'
export const PA_EXTRA_QUESTION_ANSWER = 'PA_EXTRA_QUESTION_ANSWER'
export const PA_QUESTION_ANSWER = 'PA_QUESTION_ANSWER'

export const YES = 'YES'
export const NO = 'NO'
export const DONT_KNOW = 'NOT_SURE'
